### ISSUE TITLE
Precision errors when reading csvs

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/oasis_keys_server#14]
https://github.com/OasisLMF/oasis_keys_server/blob/c0c73b666e47343c8d25bde36cc4f640f1f789a0/app.py#L176

Some of our portfolios are getting modified slightly when passing through pandas.read_csv(). For instance: 

> id,perils,coverages,agglevel1,latitude,longitude,occtype
> 1,P1.P2,B.C,ABC DEF,56.249187,-4.66883,1

The -4.66883 becomes -4.6688300000000007 instead of -4.6688299999999998 which is the nearest float. Such a small difference shouldn't matter in theory but it introduces another source of differences with other implementations of our model and pushes some points into a different areaperil_id.

This can be resolved by using `pd.read_csv(file, float_precision='round_trip')` or`pd.read_csv(file, float_precision='high')` on the line quoted above. I haven't noticed any difference in performance. As for affecting other users, the default `read_csv()` seems to be non-deterministic so changing the float-parsing method shouldn't introduce any issues that weren't already there.

**Comment by sr-murthy** [comment]
OK, I will review tomorrow.

**Comment by sr-murthy** [comment]
@carlfischerjba I created a small test CSV file containing just the lines

    id,perils,coverages,agglevel1,latitude,longitude,occtype
    1,P1.P2,B.C,ABC DEF,56.249187,-4.66883,1

and compared the difference between two dataframes
created from this file using `read_csv`, one without
any arguments except the source file and the other with
the additional argument `float_precision='high'`. I don't
notice any difference in the floats in the resulting dataframe.

    In [22]: with io.open('test.csv', 'r', encoding='utf-8') as f:
        ...:     df = pd.read_csv(io.StringIO(f.read()))
        ...:     
        ...:     

    In [23]: df.head()
    Out[23]: 
       id perils coverages agglevel1   latitude  longitude  occtype
    0   1  P1.P2       B.C   ABC DEF  56.249187   -4.66883        1

    In [24]: with io.open('test.csv', 'r', encoding='utf-8') as f:
        ...:     df2 = pd.read_csv(io.StringIO(f.read()), float_precision='high')
        ...:     
        ...:     
        ...:     

        In [25]: df2
        Out[25]: 
            id perils coverages agglevel1   latitude  longitude  occtype
    0   1  P1.P2       B.C   ABC DEF  56.249187   -4.66883        1

**Comment by sr-murthy** [comment]
Since it might make a difference to you I will implement your suggestion, and update `oasis_keys_server`. You will have to update your submodules and build a new image.

**Comment by carlfischerjba** [comment]
@sr-murthy Thanks.

If you print the specific item from the dataframe you might see the difference. See this snippet for an example.

```python
from StringIO import StringIO
import pandas as pd
input = StringIO(u'long\n-4.66883')
loc_df_default = pd.read_csv(input)
input.seek(0)
loc_df_round_trip = pd.read_csv(input, float_precision='round_trip')
input.seek(0)
loc_df_high = pd.read_csv(input, float_precision='high')
print(repr(loc_df.iloc[0,0])) # -4.6688300000000007 or -4.6688299999999998 (non-deterministic?)
print(repr(loc_df_round_trip.iloc[0,0])) # -4.6688299999999998
print(repr(loc_df_high.iloc[0,0])) # -4.6688299999999998
```
