### ISSUE TITLE
[dependencies] KeysServerTests.py

### ISSUE THREAD

**Issue by sambles** [OasisLMF/oasis_keys_server#21]
While not used in `KeysServerTests.py`  it requires the python package `pyodbc`  from importing `oasis_utils` which has features that do call `pyodbc`.

```
from oasis_utils import (
    load_ini_file,
    OasisException,
    oasis_utils,
)
```

This means the following must be installed via the systems package manager 

**For CentOS:**
```
$ sudo yum group install "Development Tools"
$ sudo yum install unixODBC 
$ sudo yum install unixODBC-devel 
```

**Comment by sr-murthy** [comment]
@sambles I would rather not have this as an open issue - dependencies are not a problem, they are quite standard. 

Maybe you should add this as a note in the requirements section in the repository README.
